### ISSUE TITLE
TODO: Drivers y primitivas

### ISSUE THREAD

**Issue by damiMela** [damiMela/REUM#1]
- [x] Pinsel/pinmode 
- [x] GPIO (read adn wriite)
- [x] Entradas antirebote
- [x] Timers
- [x] ADC
- [x] PWM
- [x] Driver comunicación serial
- [x] Scheduler
- [ ] Comunicación I2c
- [ ] Display LCD
- [ ] pasar drivers a primitivas para que usuario no interactue con drivers
